from rest_framework.authentication import SessionAuthentication
from rest_framework.viewsets import ModelViewSet

from ecommerce.shipping.models import Shipping
from ecommerce.shipping.serializers.shipping_seriali